name: JouTakTemplate
version: 1.0-SNAPSHOT
main: org.joutak.joutaktemplate.JouTakTemplate
api-version: 1.20
commands:
  givepass:
    description: Раздаёт проходки игрокам на N дней
    usage: /givepass <days>
